DROP SCHEMA IF EXISTS `gim`;
CREATE SCHEMA IF NOT EXISTS `gim` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE mysql;
DELETE FROM user WHERE User='gim' AND Host='%';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON gim.* TO 'gim'@'%' IDENTIFIED BY 'gim';
